/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/bin/bash:1: invalid multibyte char (UTF-8)
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Operation timed out - connect(2) for "sh2-d-ftp.newscyclecloud.com" port 21 (Errno::ETIMEDOUT)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Operation timed out - connect(2) for "sh2-d-ftp.newscyclecloud.com" port 21 (Errno::ETIMEDOUT)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Connection refused - connect(2) for "sh2-d-ftp.newscyclecloud.com" port 21 (Errno::ECONNREFUSED)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Connection refused - connect(2) for "sh2-d-ftp.newscyclecloud.com" port 21 (Errno::ECONNREFUSED)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Operation timed out - connect(2) for "sh2-d-ftp.newscyclecloud.com" port 21 (Errno::ETIMEDOUT)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Operation timed out - connect(2) for "52.2.199.242" port 5075 (Errno::ETIMEDOUT)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:408:in `transfercmd'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:547:in `block (2 levels) in storbinary'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:199:in `with_binary'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:546:in `block in storbinary'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:545:in `storbinary'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:694:in `putbinaryfile'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:722:in `put'
	from deploy.rb:20:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `initialize': Operation timed out - connect(2) for "sh2-d-ftp.newscyclecloud.com" port 21 (Errno::ETIMEDOUT)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `open'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:228:in `block in open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:223:in `open_socket'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:248:in `block in connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:247:in `connect'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:160:in `initialize'
	from deploy.rb:15:in `new'
	from deploy.rb:15:in `<main>'
/Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:327:in `getresp': 550 Command STOR failed: File locked (Net::FTPPermError)
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:352:in `block in sendcmd'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:350:in `sendcmd'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:415:in `transfercmd'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:547:in `block (2 levels) in storbinary'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:199:in `with_binary'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:546:in `block in storbinary'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:545:in `storbinary'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:694:in `putbinaryfile'
	from /Users/chris/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/ftp.rb:722:in `put'
	from deploy.rb:19:in `<main>'
